export const images = [
  "sekhou5 3.jpg",
  "nass3-test_tache 3.jpg",
  "ROSE61 4.jpg",
  "angeleprint2.jpg",
  "isadora1_5.jpg",
  "armande1_finale_2.jpg",
  "ROSE9 2.jpg",
  "dustin1_finale.jpg",
  "NoelleNUM2 5.jpg",
  "self1_finale2.jpg",
  "teo6_2.jpg",
  "isadora1_6 2.jpg",
  "matthias6_3 2.jpg",
  "TEO.jpg",
  "isadora7_3.jpg",
  "sekhou6 2.jpg",
  "dustin6_2.jpg",
  "matthias5_1 2.jpg",
  "nassim2.jpg",
  "teo final 3 copie 2.jpg"
];